{{ if (eq (lower .Params.INGRESS_ENABLED) "true") }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Name }}-{{ .Params.APPLICATION_NAME }}"
  namespace: "{{ .Namespace }}"
{{ if .Params.INGRESS_ANNOTATIONS }}
  annotations:
{{ range $key, $value := .Params.INGRESS_ANNOTATIONS}}
    {{ $key }}: {{ $value }}
{{ end }}
{{ end }}
spec:
  rules:
{{ if .Params.HOSTNAMES }}
{{ range .Params.HOSTNAMES}}
  - host: {{ . }}
    http:
      paths:
      - backend:
          serviceName: "{{ $.Name }}-{{ $.Params.APPLICATION_NAME }}"
{{ if $.Params.SERVICE_PORT }}
          servicePort: {{ $.Params.SERVICE_PORT }}
{{ else }}
          servicePort: {{ $.Params.PORT }}
{{ end }}
{{ end }}

{{ else }}
  - http:
      paths:
      - backend:
          serviceName: "{{ $.Name }}-{{ $.Params.APPLICATION_NAME }}"
{{ if $.Params.SERVICE_PORT }}
          servicePort: {{ $.Params.SERVICE_PORT }}
{{ else }}
          servicePort: {{ $.Params.PORT }}
{{ end }}

{{ end }}

{{ end }}