apiVersion: v1
kind: Service
metadata:
  name: "{{ .Name }}-{{ .Params.APPLICATION_NAME }}"
  namespace: "{{ .Namespace }}"
spec:
  type: {{ .Params.SERVICE_TYPE }}
  selector:
    app: "{{ .Name }}-{{ .Params.APPLICATION_NAME }}"
  ports:
    - protocol: TCP
{{ if .Params.SERVICE_PORT }}
      port: {{ .Params.SERVICE_PORT }}
{{ else }}
      port: {{ .Params.PORT }}
{{ end }}
      targetPort: {{ .Params.PORT }}